import { useMemo, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import { useIssueReports } from '../context/IssueReportsContext'

export function AssetsPage() {
  const { reports, removeReport } = useIssueReports()
  const [selectedId, setSelectedId] = useState<string | null>(null)

  const selected = useMemo(
    () => reports.find((r) => r.id === selectedId) ?? null,
    [reports, selectedId],
  )

  return (
    <div className="page">
      <div className="page-header">
        <h1 className="page-title">Assets</h1>
        <p className="page-lead">
          Issue reports generated by the Report generation agent from incident chat. Stored in this
          browser only (localStorage).
        </p>
      </div>

      <div className="assets-layout">
        <section className="assets-list-panel" aria-label="Saved reports">
          {reports.length === 0 ? (
            <p className="assets-empty">
              No reports yet. Open an issue, use <strong>Chat with agent</strong>, and ask for an
              issue report.
            </p>
          ) : (
            <ul className="assets-list">
              {reports.map((r) => (
                <li key={r.id}>
                  <button
                    type="button"
                    className={`assets-list-item${selectedId === r.id ? ' assets-list-item--active' : ''}`}
                    onClick={() => setSelectedId(r.id)}
                  >
                    <span className="assets-list-title">{r.issueTitle}</span>
                    <span className="assets-list-meta">
                      {r.createdAt.slice(0, 19).replace('T', ' ')} · Issue {r.issueId}
                    </span>
                  </button>
                  <button
                    type="button"
                    className="assets-list-delete"
                    aria-label={`Delete report ${r.issueTitle}`}
                    onClick={() => {
                      removeReport(r.id)
                      setSelectedId((cur) => (cur === r.id ? null : cur))
                    }}
                  >
                    Remove
                  </button>
                </li>
              ))}
            </ul>
          )}
        </section>

        <section className="assets-preview-panel" aria-label="Report preview">
          {!selected ? (
            <p className="assets-preview-placeholder">
              Select a report to preview Markdown, or generate one from an issue chat.
            </p>
          ) : (
            <article className="assets-report-md">
              <header className="assets-report-header">
                <h2 className="assets-report-h2">{selected.issueTitle}</h2>
                <p className="assets-report-sub">
                  Report ID <code>{selected.id}</code> · Issue <code>{selected.issueId}</code>
                </p>
              </header>
              <ReactMarkdown>{selected.markdown}</ReactMarkdown>
            </article>
          )}
        </section>
      </div>
    </div>
  )
}
